### ISSUE TITLE
Boar-notes finalized 

### ISSUE THREAD

**Issue by BrassMcCrafty** [BrassAmber-Mods/ClassicHostiles#8]
- [x] hostile mobs that run at the player and have armor penetration
- [x] breeds with another boar upon successful kill of animal/player
- [x] spawns: all hours, on a constant hunt
- [x] group size: 2-4

Biomes
is_plains
is_desert
is_forest
is mountains
is_jungle
-no cold biomes

**Comment by Xratedjunior** [comment]
boar
is_plains
is_desert
is_forest
is mountains
is_jungle
-no cold biomes
